build: Dependency bump (#1037)
Signed-off-by: oliver könig <okoenig@nvidia.com>
Signed-off-by: Charlie Truong <chtruong@nvidia.com>
Co-authored-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/build-test-publish-wheel.yml b/.github/workflows/build-test-publish-wheel.yml
--- a/.github/workflows/build-test-publish-wheel.yml
+++ b/.github/workflows/build-test-publish-wheel.yml
@@ -37,53 +37,53 @@ jobs:
   pre-flight:
     uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_cicd_preflight.yml@v0.64.2
 
-  build-test-publish-wheel:
-    needs: [pre-flight]
-    if: |
-      !(needs.pre-flight.outputs.docs_only == 'true'
-      || needs.pre-flight.outputs.is_deployment_workflow == 'true')
-    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_build_test_publish_wheel.yml@v0.65.1
-    with:
-      dry-run: true
-      python-package: megatron.bridge
-      python-version: "3.10"
-      packaging: uv
-      no-publish: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/r')) }}
-      has-src-dir: true
-      skip-test-wheel: true
-      custom-container: nvcr.io/nvidia/pytorch:25.05-py3
-      runner: self-hosted-nemo
-      no-build-isolation: true
-      submodules: recursive
-      container-options: "--gpus all --runtime=nvidia"
-    secrets:
-      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
-      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
-      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
-      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
-      GH_TOKEN: ${{ secrets.PAT }}
+  # build-test-publish-wheel:
+  #   needs: [pre-flight]
+  #   if: |
+  #     !(needs.pre-flight.outputs.docs_only == 'true'
+  #     || needs.pre-flight.outputs.is_deployment_workflow == 'true')
+  #   uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_build_test_publish_wheel.yml@v0.65.1
+  #   with:
+  #     dry-run: true
+  #     python-package: megatron.bridge
+  #     python-version: "3.10"
+  #     packaging: uv
+  #     no-publish: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/r')) }}
+  #     has-src-dir: true
+  #     skip-test-wheel: true
+  #     custom-container: nvcr.io/nvidia/pytorch:25.05-py3
+  #     runner: self-hosted-nemo
+  #     no-build-isolation: true
+  #     submodules: recursive
+  #     container-options: "--gpus all --runtime=nvidia"
+  #   secrets:
+  #     TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
+  #     TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
+  #     SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
+  #     SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
+  #     GH_TOKEN: ${{ secrets.PAT }}
 
-  build-test-publish-wheel-summary:
-    needs: [pre-flight, build-test-publish-wheel]
-    if: |
-      (
-        needs.pre-flight.outputs.docs_only == 'true'
-        || needs.pre-flight.outputs.is_deployment_workflow == 'true'
-        || always()
-      )
-      && !cancelled()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Result
-        run: |
-          FAILED_JOBS=$(gh run view $GITHUB_RUN_ID --json jobs --jq '[.jobs[] | select(.status == "completed" and .conclusion != "success")] | length') || echo 0
+  # build-test-publish-wheel-summary:
+  #   needs: [pre-flight, build-test-publish-wheel]
+  #   if: |
+  #     (
+  #       needs.pre-flight.outputs.docs_only == 'true'
+  #       || needs.pre-flight.outputs.is_deployment_workflow == 'true'
+  #       || always()
+  #     )
+  #     && !cancelled()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Result
+  #       run: |
+  #         FAILED_JOBS=$(gh run view $GITHUB_RUN_ID --json jobs --jq '[.jobs[] | select(.status == "completed" and .conclusion != "success")] | length') || echo 0
 
-          if [ "${FAILED_JOBS:-0}" -eq 0 ] || [ "$SKIPPING_IS_ALLOWED" == "true" ]; then
-              echo "✅ All previous jobs completed successfully"
-              exit 0
-          else
-              echo "❌ Found $FAILED_JOBS failed job(s)"
-              # Show which jobs failed
-              gh run view $GITHUB_RUN_ID --json jobs --jq '.jobs[] | select(.status == "completed" and .conclusion != "success") | .name'
-              exit 1
-          fi
+  #         if [ "${FAILED_JOBS:-0}" -eq 0 ] || [ "$SKIPPING_IS_ALLOWED" == "true" ]; then
+  #             echo "✅ All previous jobs completed successfully"
+  #             exit 0
+  #         else
+  #             echo "❌ Found $FAILED_JOBS failed job(s)"
+  #             # Show which jobs failed
+  #             gh run view $GITHUB_RUN_ID --json jobs --jq '.jobs[] | select(.status == "completed" and .conclusion != "success") | .name'
+  #             exit 1
+  #         fi
diff --git a/.github/workflows/install-test.yml b/.github/workflows/install-test.yml
--- a/.github/workflows/install-test.yml
+++ b/.github/workflows/install-test.yml
@@ -32,60 +32,60 @@ jobs:
   pre-flight:
     uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_cicd_preflight.yml@v0.64.2
 
-  pip-test-pytorch:
-    needs: [pre-flight]
-    if: |
-      !(needs.pre-flight.outputs.docs_only == 'true'
-      || needs.pre-flight.outputs.is_deployment_workflow == 'true')
-    runs-on: self-hosted-nemo
-    name: Pip - Python${{ matrix.python-version }}${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }} - AMD64/Linux - NGC PyTorch
-    container:
-      image: nvcr.io/nvidia/pytorch:25.05-py3
-    environment: nemo-ci
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.12"]
-        extra-groups: ["", "recipes"]
-    env:
-      EXTRA: ${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }}
-    steps:
-      - name: Install git
-        shell: bash -x -e -u -o pipefail {0}
-        run: |
-          apt-get update
-          apt-get install -y git
+  # pip-test-pytorch:
+  #   needs: [pre-flight]
+  #   if: |
+  #     !(needs.pre-flight.outputs.docs_only == 'true'
+  #     || needs.pre-flight.outputs.is_deployment_workflow == 'true')
+  #   runs-on: self-hosted-nemo
+  #   name: Pip - Python${{ matrix.python-version }}${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }} - AMD64/Linux - NGC PyTorch
+  #   container:
+  #     image: nvcr.io/nvidia/pytorch:25.05-py3
+  #   environment: nemo-ci
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.12"]
+  #       extra-groups: ["", "recipes"]
+  #   env:
+  #     EXTRA: ${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }}
+  #   steps:
+  #     - name: Install git
+  #       shell: bash -x -e -u -o pipefail {0}
+  #       run: |
+  #         apt-get update
+  #         apt-get install -y git
 
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
 
-      - name: Set PATH
-        run: |
-          echo "UV_PROJECT_ENVIRONMENT=/opt/venv" | tee -a "$GITHUB_ENV"
-          echo "UV_LINK_MODE=copy" | tee -a "$GITHUB_ENV"
-          echo "CUDA_HOME=/usr/local/cuda" | tee -a "$GITHUB_ENV"
-          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" | tee -a "$GITHUB_ENV"
-          echo "PATH=$HOME/.local/bin:$PATH:$CUDA_HOME/bin" | tee -a "$GITHUB_ENV"
-          echo "TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0;7.5;8.0;8.6;9.0" | tee -a "$GITHUB_ENV"
+  #     - name: Set PATH
+  #       run: |
+  #         echo "UV_PROJECT_ENVIRONMENT=/opt/venv" | tee -a "$GITHUB_ENV"
+  #         echo "UV_LINK_MODE=copy" | tee -a "$GITHUB_ENV"
+  #         echo "CUDA_HOME=/usr/local/cuda" | tee -a "$GITHUB_ENV"
+  #         echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" | tee -a "$GITHUB_ENV"
+  #         echo "PATH=$HOME/.local/bin:$PATH:$CUDA_HOME/bin" | tee -a "$GITHUB_ENV"
+  #         echo "TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0;7.5;8.0;8.6;9.0" | tee -a "$GITHUB_ENV"
 
-      - name: Install megatron-bridge${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }}
-        shell: bash -x -e -u -o pipefail {0}
-        run: bash docker/common/install.sh --base-image pytorch --python-version ${{ matrix.python-version }}
+  #     - name: Install megatron-bridge${{ matrix.extra-groups != '' && format('[{0}]', matrix.extra-groups) || '' }}
+  #       shell: bash -x -e -u -o pipefail {0}
+  #       run: bash docker/common/install.sh --base-image pytorch --python-version ${{ matrix.python-version }}
 
-      - name: Checkout check-imports
-        uses: actions/checkout@v4
-        with:
-          repository: NVIDIA-NeMo/FW-CI-templates
-          ref: v0.39.0
-          path: FW-CI-templates
+  #     - name: Checkout check-imports
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: NVIDIA-NeMo/FW-CI-templates
+  #         ref: v0.39.0
+  #         path: FW-CI-templates
 
-      - name: Check imports for megatron-bridge
-        uses: ./FW-CI-templates/.github/actions/check-imports
-        with:
-          package-name: megatron.bridge
-          python-binary: ${{ env.UV_PROJECT_ENVIRONMENT }}/bin/python
+  #     - name: Check imports for megatron-bridge
+  #       uses: ./FW-CI-templates/.github/actions/check-imports
+  #       with:
+  #         package-name: megatron.bridge
+  #         python-binary: ${{ env.UV_PROJECT_ENVIRONMENT }}/bin/python
 
   uv-test-pytorch:
     needs: [pre-flight]
@@ -129,7 +129,7 @@ jobs:
         run: bash docker/common/install.sh --base-image pytorch --use-uv
 
   install-test-summary:
-    needs: [pre-flight, pip-test-pytorch, uv-test-pytorch]
+    needs: [pre-flight, uv-test-pytorch]
     runs-on: ubuntu-latest
     name: Install test summary
     if: |
